spring:
  config:
    activate: 
      on-profile: prod
build:
  version: 1.0.0
cards:
  message: "Welcome to EazyBank Cards related local APIs "
  contactDetails:
    name: "Shadab - Developer"
    email: "shadab@eazybank.com"
  onCallSupport:
    - (555) 555-9938
    - (555) 523-8873