spring:
  config:
    activate: 
      on-profile: qa
  datasource:
    url: jdbc:postgresql://localhost:5432/MicroServiceAccounts
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Options: create, create-drop, update, validate, none
    show-sql: true      # Set to false in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Set to false in production

build:
  version: 2.0.0
cards:
  message: "Welcome to EazyBank Cards related local APIs "
  contactDetails:
    name: "Rayhan - Developer"
    email: "rayhan@eazybank.com"
  onCallSupport:
    - (555) 555-2765
    - (555) 523-3726