services:
  accounts:
    image: saqlenpasha1/accounts:v1
    container_name: accounts
    ports:
      - "8080:8080"
    deploy:
      resources:
            limits:
              memory: 700M
    networks:
      - easybank	
  cards:
    image: saqlenpasha1/cards:v1
    container_name: cards
    ports:
     - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - easybank
  loans:
    image: saqlenpasha1/loans:v1
    container_name: loans
    ports:
     - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - easybank
networks:
  easybank:
   driver: "bridge"
